apiVersion: v2
description: Cilium ServiceMonitors
name: cilium-servicemonitors
version: 0.1.4
appVersion: 1.0.0
icon: https://s.giantswarm.io/app-icons/cilium/1/dark.svg
annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.restrictions.cluster-singleton: "true"
  io.giantswarm.application.restrictions.fixed-namespace: kube-system
home: https://github.com/giantswarm/cilium-servicemonitors-app
keywords:
  - monitoring
type: application
